export * from "./listsActions";
export * from "./cardsActions";
export * from "./boardActions";
export * from "./auth";

export const CONSTANTS = {
  ADD_CARD: "ADD_CARD",
  ADD_LIST: "ADD_LIST",
  DRAG_HAPPENED: "DRAG_HAPPENED",
  EDIT_CARD: "EDIT_CARD",
  DELETE_CARD: "DELETE_CARD",
  ADD_BOARD: "ADD_BOARD",
  
  GET_BOARD: "GET_BOARD",
  GET_LISTS: "GET_LISTS",
  GET_CARDS: "GET_CARDS",


  GET_BOARDSLIST: "GET_BOARDSLIST",
  GET_BOARDSORDER: "GET_BOARDSORDER",

  GET_LISTSORDER: "GET_LISTSORDER",
  DELETE_LIST: "DELETE_LIST",
  EDIT_LIST_TITLE: "EDIT_LIST_TITLE",
  EDIT_CARD_TASK: "EDIT_CARD_TASK",

  SORT_CARDS_IN_SAME_LIST: "SORT_CARDS_IN_SAME_LIST",

  GET_ERRORS: 'GET_ERRORS',
  CREATE_MESSAGE: 'CREATE_MESSAGE',

  USER_LOADING : 'USER_LOADING',
  USER_LOADED : 'USER_LOADED',
  AUTH_ERROR : 'AUTH_ERROR',
  LOGIN_SUCCESS : 'LOGIN_SUCCESS',
  LOGIN_FAIL : 'LOGIN_FAIL',
  LOGOUT_SUCCESS : 'LOGOUT_SUCCESS',
  REGISTER_SUCCESS : 'REGISTER_SUCCESS',
  REGISTER_FAIL : 'REGISTER_FAIL',
};
