# Generated by Django 3.1.7 on 2021-04-01 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='string_id',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
