# Generated by Django 3.1.7 on 2021-04-07 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_auto_20210401_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='string_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
