# Generated by Django 3.1.7 on 2021-04-26 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('boards', '0003_auto_20210407_1755'),
        ('lists', '0002_auto_20210407_1800'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.TextField()),
                ('order_num', models.IntegerField(blank=True, null=True)),
                ('string_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('board', models.ForeignKey(default=7, on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='boards.board')),
                ('list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='lists.list')),
            ],
        ),
    ]
