# Generated by Django 3.1.7 on 2021-05-04 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_auto_20210426_1801'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='card',
            options={'ordering': ['order_num']},
        ),
    ]
